
CREATE TABLE IF NOT EXISTS T_USER (
	UID INTEGER PRIMARY KEY,
	UNAME VARCHAR(25) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	UISGN VARCHAR(250),
	SEX INTEGER CHECK(SEX = 1 OR SEX = 2),
	UNIQUE(UNAME)
);
CREATE INDEX INDEX_UNAME ON T_USER(UNAME);
CREATE INDEX INDEX_PSWORD ON T_USER(PASSWORD);\