/**
 * SQL
 */
const { Mark } = Coralian.constants;
const { Span } = require("./../constants");
const { doBlockComment4CLike, doLineComment4Like, doHtmlEscape, doNewLineJoin, append } = require("./../components");
const common = require("./../common");


common.addLang([{ name: "SQL" }], null, {
	doComment: function (code, index, len, at, output) {
		let next = code.charAt(index + 1);
		if (at === Mark.SLASH && next === Mark.ASTERISK) {
			index = doBlockComment4CLike(code, index, len, output);
		} else if (at == Mark.HYPHEN && next === Mark.HYPHEN) {
			index = doLineComment4Like(code, index, len, at, output);
		} else {
			doHtmlEscape(at, output);
		}
		return index;
	},
	judgeComment: function (at) {
		return at === Mark.SLASH || at === Mark.HYPHEN;
	},
	charSpan: Span.STRING,
	doChar: function (code, index, len, output, escaper, end, span) {

		append(output, span + code.charAt(index++));
		let next = code.charAt(index + 1);

		for (; index < len; index++) {
			let at = code.charAt(index);

			if (at === Mark.NEW_LINE) {
				doNewLineJoin(output, span);
			} else {
				doHtmlEscape(at, output);
				if (at === end) {
					next = code.charAt(index + 1);
					if (next === end) { // 转义符号
						doHtmlEscape(next, output);
						index++;
					} else { // 字符串结束
						break;
					}
				}
			}
		}
		append(output, Span.CLOSE);
		doHtmlEscape(next, output);

		return index;
	},
	escaper: Mark.QUOTE,
	charCaseMethod: "toUpperCase"
}, [
"ABORT","ABS","ACCESS","AGGREGATE","ALL","ALLOCATE","ALSO","ALTER","ANALYSE","ANALYZE","AND","ANY","ARE","ARRAY","ARRAY_AGG","ARRAY_MAX_CARDINALITY","AS","ASENSITIVE","ASYMMETRIC","AT","ATOMIC","ATTRIBUTES","AUTHORIZATION","AVG","BACKWARD","BEGIN","BEGIN_FRAME","BEGIN_PARTITION","BETWEEN","BIGINT","BINARY","BIT","BIT_LENGTH","BLOB","BOOLEAN","BOTH","BY","CACHE","CALL","CALLED","CARDINALITY","CASCADED","CASE","CAST","CEIL","CEILING","CHAR","CHARACTER","CHARACTER_LENGTH","CHAR_LENGTH","CHECK","CHECKPOINT","CLASS","CLOB","CLOSE","CLUSTER","COALESCE","COLLATE","COLLECT","COLUMN","COMMENT","COMMENTS","COMMIT","CONCURRENTLY","CONDITION","CONFIGURATION","CONNECT","CONSTRAINT","CONTAINS","CONVERSION","CONVERT","COPY","CORR","CORRESPONDING","COST","COUNT","COVAR_POP","COVAR_SAMP","CREATE","CROSS","CSV","CUBE","CUME_DIST","CURRENT","CURRENT_CATALOG","CURRENT_DATE","CURRENT_DEFAULT_TRANSFORM_GROUP","CURRENT_PATH","CURRENT_ROLE","CURRENT_ROW","CURRENT_SCHEMA","CURRENT_TIME","CURRENT_TIMESTAMP","CURRENT_TRANSFORM_GROUP_FOR_TYPE","CURRENT_USER","CURSOR","CYCLE","DATABASE","DATALINK","DATE","DAY","DEALLOCATE","DEC","DECIMAL","DECLARE","DEFAULT","DELETE","DELIMITER","DELIMITERS","DENSE_RANK","DEREF","DESCRIBE","DETERMINISTIC","DICTIONARY","DISABLE","DISCARD","DISCONNECT","DISTINCT","DLNEWCOPY","DLPREVIOUSCOPY","DLURLCOMPLETE","DLURLCOMPLETEONLY","DLURLCOMPLETEWRITE","DLURLPATH","DLURLPATHONLY","DLURLPATHWRITE","DLURLSCHEME","DLURLSERVER","DLVALUE","DO","DOUBLE","DROP","DYNAMIC","EACH","ELEMENT","ELSE","ENABLE","ENCRYPTED","END","END-EXEC","END_FRAME","END_PARTITION","ENUM","EQUALS","ESCAPE","EVENT","EVERY","EXCEPT","EXCEPTION","EXCLUSIVE","EXEC","EXECUTE","EXISTS","EXPLAIN","EXTENSION","EXTERNAL","EXTRACT","FALSE","FAMILY","FETCH","FILTER","FIRST_VALUE","FLOAT","FLOOR","FOR","FORCE","FOREIGN","FORWARD","FRAME_ROW","FREE","FREEZE","FROM","FULL","FUNCTION","FUNCTIONS","FUSION","GET","GLOBAL","GRANT","GREATEST","GROUP","GROUPING","GROUPS","HANDLER","HAVING","HEADER","HOLD","HOUR","IDENTITY","IF","ILIKE","IMMUTABLE","IMPLICIT","IMPORT","IN","INDEX","INDEXES","INDICATOR","INHERIT","INHERITS","INLINE","INNER","INOUT","INSENSITIVE","INSERT","INT","INTEGER","INTERSECT","INTERSECTION","INTERVAL","INTO","IS","ISNULL","JOIN","LABEL","LAG","LANGUAGE","LARGE","LAST_VALUE","LATERAL","LC_COLLATE","LC_CTYPE","LEAD","LEADING","LEAKPROOF","LEAST","LEFT","LIKE","LIKE_REGEX","LISTEN","LN","LOAD","LOCAL","LOCALTIME","LOCALTIMESTAMP","LOCK","LOWER","MATCH","MATERIALIZED","MAX","MAX_CARDINALITY","MEMBER","MERGE","METHOD","MIN","MINUTE","MOD","MODE","MODIFIES","MODULE","MONTH","MOVE","MULTISET","NATIONAL","NATURAL","NCHAR","NCLOB","NEW","NO","NONE","NORMALIZE","NOT","NOTHING","NOTIFY","NOTNULL","NOWAIT","NTH_VALUE","NTILE","NULL","NULLIF","NUMERIC","OCCURRENCES_REGEX","OCTET_LENGTH","OF","OFFSET","OIDS","OLD","ON","ONLY","OPEN","OPERATOR","OR","ORDER","OUT","OUTER","OVER","OVERLAPS","OVERLAY","OWNED","OWNER","PARAMETER","PARSER","PARTITION","PASSWORD","PERCENT","PERCENTILE_CONT","PERCENTILE_DISC","PERCENT_RANK","PERIOD","PLANS","PORTION","POSITION","POSITION_REGEX","POWER","PRECEDES","PRECISION","PREPARE","PREPARED","PRIMARY","PROCEDURAL","PROCEDURE","PROGRAM","QUOTE","RANGE","RANK","READS","REAL","REASSIGN","RECHECK","RECURSIVE","REF","REFERENCES","REFERENCING","REFRESH","REGR_AVGX","REGR_AVGY","REGR_COUNT","REGR_INTERCEPT","REGR_R2","REGR_SLOPE","REGR_SXX","REGR_SXY","REGR_SYY","REINDEX","RELEASE","RENAME","REPLACE","REPLICA","RESET","RESULT","RETURN","RETURNED_CARDINALITY","RETURNS","REVOKE","RIGHT","ROLLBACK","ROLLUP","ROW","ROWS","ROW_NUMBER","RULE","SAVEPOINT","SCOPE","SCROLL","SEARCH","SECOND","SELECT","SENSITIVE","SEQUENCES","SESSION_USER","SET","SETOF","SHARE","SHOW","SIMILAR","SMALLINT","SNAPSHOT","SOME","SPECIFIC","SPECIFICTYPE","SQL","SQLCODE","SQLERROR","SQLEXCEPTION","SQLSTATE","SQLWARNING","SQRT","STABLE","START","STATIC","STATISTICS","STDDEV_POP","STDDEV_SAMP","STDIN","STDOUT","STORAGE","STRICT","SUBMULTISET","SUBSTRING","SUBSTRING_REGEX","SUCCEEDS","SUM","SYMMETRIC","SYSID","SYSTEM","SYSTEM_TIME","SYSTEM_USER","TABLE","TABLES","TABLESAMPLE","TABLESPACE","TEMP","TEMPLATE","TEXT","THEN","TIME","TIMESTAMP","TIMEZONE_HOUR","TIMEZONE_MINUTE","TO","TRAILING","TRANSLATE","TRANSLATE_REGEX","TRANSLATION","TREAT","TRIGGER","TRIM","TRIM_ARRAY","TRUE","TRUNCATE","TRUSTED","TYPES","UESCAPE","UNENCRYPTED","UNION","UNIQUE","UNKNOWN","UNLISTEN","UNLOGGED","UNNEST","UNTIL","UPDATE","UPPER","USER","USING","VACUUM","VALIDATE","VALIDATOR","VALUE","VALUES","VALUE_OF","VARBINARY","VARCHAR","VARIADIC","VARYING","VAR_POP","VAR_SAMP","VERBOSE","VERSIONING","VOLATILE","WHEN","WHENEVER","WHERE","WIDTH_BUCKET","WINDOW","WITH","WITHIN","WITHOUT","XML","XMLAGG","XMLATTRIBUTES","XMLBINARY","XMLCAST","XMLCOMMENT","XMLCONCAT","XMLDOCUMENT","XMLELEMENT","XMLEXISTS","XMLFOREST","XMLITERATE","XMLNAMESPACES","XMLPARSE","XMLPI","XMLQUERY","XMLROOT","XMLSERIALIZE","XMLTABLE","XMLTEXT","XMLVALIDATE","YEAR"
]);